export const GET_HEROES_STARTED = "GET_HEROES_STARTED"
export const GET_HEROES_SUCCESS = "GET_HEROES_SUCCESS"
export const GET_HEROES_FAILURE = "GET_HEROES_FAILURE"

export const GET_PHOTOS_STARTED = "GET_PHOTOS_STARTED"
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS"
export const GET_PHOTOS_FAILURE = "GET_PHOTOS_FAILURE"

export const POST_HERO_STARTED = "POST_HERO_STARTED"
export const POST_HERO_SUCCESS = "POST_HERO_SUCCESS"
export const POST_HERO_FAILURE = "POST_HERO_FAILURE"

export const DELETE_HERO_STARTED = "DELETE_HERO_STARTED"
export const DELETE_HERO_SUCCESS = "DELETE_HERO_SUCCESS"
export const DELETE_HERO_FAILURE = "DELETE_HERO_FAILURE"

export const PATCH_HERO_STARTED = "PATCH_HERO_STARTED"
export const PATCH_HERO_SUCCESS = "PATCH_HERO_SUCCESS"
export const PATCH_HERO_FAILURE = "PATCH_HERO_FAILURE"