export const GET_HEROES_STARTED = "GET_HEROES_STARTED"
export const GET_HEROES_SUCCESS = "GET_HEROES_SUCCESS"
export const GET_HEROES_FAILURE = "GET_HEROES_FAILURE"

export const GET_PHOTOS_STARTED = "GET_PHOTOS_STARTED"
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS"
export const GET_PHOTOS_FAILURE = "GET_PHOTOS_FAILURE"

export const GET_AVATAR_STARTED = "GET_AVATAR_STARTED"
export const GET_AVATAR_SUCCESS = "GET_AVATAR_SUCCESS"
export const GET_AVATAR_FAILURE = "GET_AVATAR_FAILURE"


export const SET_HERO_STARTED = "SET_HERO_STARTED"
export const SET_HERO_SUCCESS = "SET_HERO_SUCCESS"
export const SET_HERO_FAILURE = "SET_HERO_FAILURE"

export const SET_HERO = "SET_HERO"

export const POST_HERO_STARTED = "POST_HERO_STARTED"
export const POST_HERO_SUCCESS = "POST_HERO_SUCCESS"
export const POST_HERO_FAILURE = "POST_HERO_FAILURE"



