export const GET_HEROES_STARTED = "GET_HEROES_STARTED"
export const GET_HEROES_SUCCESS = "GET_HEROES_SUCCESS"
export const GET_HEROES_FAILURE = "GET_HEROES_FAILURE"

export const GET_PHOTOS_STARTED = "GET_PHOTOS_STARTED"
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS"
export const GET_PHOTOS_FAILURE = "GET_PHOTOS_FAILURE"

export const GET_AVATAR_STARTED = "GET_AVATAR_STARTED"
export const GET_AVATAR_SUCCESS = "GET_AVATAR_SUCCESS"
export const GET_AVATAR_FAILURE = "GET_AVATAR_FAILURE"